### ISSUE TITLE
White screen when used with Dissolution

### ISSUE THREAD

**Issue by Derpford** [DonBruce64/RealFirstPersonRender#14]
Upon dying with the Remnant soul in Dissolution, the screen goes white. Hitting F1 fixes this, but any mode that renders anything goes fully white.

**Comment by Derpford** [comment]
Update: Looks like this only happens while there's a HUD element visible (i.e., if I hit F1 until there's no HUD elements displayed, everything works, but if I open the chatbox or pause the game I get a white screen).

**Comment by DonBruce64** [comment]
Odd, and you say this only happens when RFPR is installed?

Also, what exactly does the Remnant soul in Dissolution do?  Would be helpful to have background on that for me to figure out how it might be conflicting.

**Comment by Derpford** [comment]
Yeah, this only happens with RFPR.

As for what the Remnant soul does: Dissolution has an akternative death
mechanic. At world creation, you can choose to have a "Remnant" soul, and
instead of simply respawning, you will become a ghost at death. While in a
ghostly form, you are transparent, you can fly, and you slowly lose XP. You
must possess an undead creature in order to return to the corporeal world;
this leaves you with all the drawbacks of being a zombie, but with the
advantage of being alive and near your body. Upon consuming human flesh,
you turn back into a human again.

As a side note, RFPR is *also* broken when possessing a zombie, but only in
that you can't see your new body. The white screen bug is no longer present
once you have a body and you can continue as normal from there.

**Comment by DonBruce64** [comment]
Ah, I bet I know what this is about.  Given that you are getting a white screen rendering HUD elements, and that Dissolution is rendering you as transparent when a ghost, I'm willing to bet it's not setting transparency right after it's done messing with the player rendering in first-person as it doesn't expect that to ever happen.  At that point nothing would be the matter, except Minecraft doesn't expect the transparency to be in the state it's in when rendering the HUD, so instead of rendering a transparent overlay it renders white.

I'm not sure how to combat this on the RFPR side, as it's directly related to rendering OpenGL calls that happen on the player rendering side, that it looks like Dissolution is messing with.  You might want to get with them on this issue to see if they have any idea how rendering the player's model while in first-person would affect them like how I do now.  Perhaps you could encourage them to test with RFPR installed and see if there's anything we can do together to get this patched?

**Comment by Pyrofab** [comment]
Does RFPR fire pre and post render player events ? If so, I should be reverting the transparency already

**Comment by DonBruce64** [comment]
Yes.  I directly call RenderPlayer.doRender(), which itself calls RenderPlayerEvent.Pre() and RenderPlayerEvent.Post() on the Forge event system.  I don't do any GL calls at all in my code, but there's no telling if MC is doing something while in first-person that your code doesn't expect.  If you think it would help I could compile a test version with the doRender call commented out to see if its related to the actual rendering or the only setting up of the render.

**Comment by DonBruce64** [comment]
Closing this ticket as this happens with both Forge and Fabric versions of RFPR when installed with Dissolution.  Additionally, as RFPR 2 exists this code is essentially obsolete and will no-longer be maintained by me.
