### ISSUE TITLE
crash if re-enter server while dead, 

### ISSUE THREAD

**Issue by Redd56** [DonBruce64/RealFirstPersonRender#16]
if you die, then try to re-enter a server without respawning first it will crash you with a good old null pointer exception of: https://pastebin.com/bZUXJ0bf

**Comment by DonBruce64** [comment]
This crash report is not from my version of the mod.  It says
`java.lang.NullPointerException: Rendering entity in world
	at kenijey.realrender.RenderPlayerDummy.func_76986_a(RenderPlayerDummy.java:26)`

Kenijey made another version of RFPR, the Curse page to which is here: https://minecraft.curseforge.com/projects/first-person-render

It appears that he removed his GitHub page, and the YouTube video, however, which makes me think he's not going to maintain it anymore.  Either way, since it's not my code, there's nothing I can do about it.

**Comment by Redd56** [comment]
Oh my bad, no wonder its laggy and buggy
