### ISSUE TITLE
Only disable the arm of the item held

### ISSUE THREAD

**Issue by WolfieWaffle** [DonBruce64/RealFirstPersonRender#3]
When you hold say a compass, it disables the 3d render of both arms. It might be ideal to include an option, perhaps per item, that says if it disables both arms or only the arm the item in question is being held in.

**Comment by DonBruce64** [comment]
Not really sure how to do this, as many items can be held in the offhand as well as the main hand, and RFPR doesn't know what items are held in what hands; it only knows if a "blacklisted" item is in *any* hand.  Because of this, and the general retirement of this mod and the other feller taking up the mantle, I'm closing this issue as a not-gonna-do.
