### ISSUE TITLE
Mod Compability: Baubles

### ISSUE THREAD

**Issue by Morinor** [DonBruce64/RealFirstPersonRender#6]
The head baubles are rendered.
As baubles is a pretty popular mod, it might be a good idea to fix this.
Of course, there are more mods that add additional head slots, like Cosmetic Armor, Galacticraft etc.
Maybe some way of blacklisting certain slots would be neat.

**Comment by DonBruce64** [comment]
This is not something I want to tackle.  RFPR works by simply calling the render routines that are already built-in to Minecraft for rendering the player.  Prior to these calls, I check the armor slots (that are part of the player inventory) for head armor and remove it.  This works well for preventing such items from rendering, even if another mod runs code during the render routine that does extra rendering based on those items.

Baubles does things differently.  From what I can see of their source code, they don't use inventory in the traditional way.  Rather, they have a custom inventory that you can only access through their API, which means RFPR would have to compile itself with that API to ensure the head baubles aren't rendered.  This is potentially hazardous because if Baubles updates its API, then RFPR will crash when trying to run on newer versions and will have to be updated as well.  The same is likely the case for other custom-head-slot mods, which means RFPR would have to import EVERY mod with custom inventory slots to be compatible.

That being said, there's no way for THOSE mods to know that RFPR is inhibiting the rendering of head-stuffs because all it does is remove regular armor, which isn't abnormal and shouldn't affect their code either.  Truly, the only way to fix this is on the RFPR side, but I don't want to start creating dependencies in a codebase I rarely update (not to mention I'm not good at that to begin with).  This code is open-source and free for anyone to modify, however, so if anyone wishes to go down that road may do so with my blessing.
